version: '3'
services:
    sonar:
        build: ../sonar
        depends_on:
            - ui
            - proxy
    ui:
        build:
          context: ../ui
          dockerfile: Dockerfile-local
        # We can't mount the entire UI directory, since JavaScript dependencies
        # (`node_modules`) live at that location.
        volumes:
            - ../ui/src:/usr/local/src/skiff/app/ui/src
            - ../ui/public:/usr/local/src/skiff/app/ui/public
            - ../ui/package.json:/usr/local/src/skiff/app/ui/package.json
            - ../ui/tsconfig.json:/usr/local/src/skiff/app/ui/tsconfig.json
            - ../ui/yarn.lock:/usr/local/src/skiff/app/ui/yarn.lock
    proxy:
        build: ./proxy
        ports:
            - 8080:80
        depends_on:
            - ui
        extra_hosts:
            - "host.docker.internal:host-gateway"
        # network_mode: host

